import {state,connected,request,refresh,recordFor} from './state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let screen='simulation',reviewFilter='duplicates',reviewSearch='',dataTab='questions',activeProposal=null,dialogAction=null;
const pby=id=>state.products.find(p=>p.id===id),vby=id=>state.variants.find(v=>v.id===id),sby=id=>state.slots.find(s=>s.id===id);
const nameFor=id=>{const v=vby(id);return v?pby(v.product_id)?.name:'Unassigned';};
const slotName=id=>sby(id)?.title||id;
const chip=(s,cls='')=>`<span class="pill ${cls}">${esc(s)}</span>`;
const btn=(label,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
const heading=(label,title,description,actions='')=>`<div class="screen-heading"><div><div class="eyebrow">APS / ${label}</div><h1>${title}</h1><p>${description}</p></div><div class="screen-actions">${actions}</div></div>`;
const imageFor=id=>{const v=state.variants.find(v=>v.product_id===id);return v?recordFor(v.id)?.texture:null;};
const photo=id=>imageFor(id)?`<img loading="lazy" src="${esc(imageFor(id))}" alt="${esc(pby(id)?.name)} face">`:'<span></span>';
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),6500);}
function updateHeader(){
  $('#connectionState').textContent=connected?`● SQLite connected · ${state.meta.operator_role}`:'◌ Published review · read only';$('#connectionState').className='baseline '+(connected?'live':'snapshot');
  $('#revisionStamp').textContent=`Source revision ${state.meta.revision} · ${state.meta.policy_version}`;
  $('#reviewBadge').textContent=state.review.summary.attention_slots;
}
function setScreen(name){screen=name;$$('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('.workspace').hidden=name!=='simulation';$('.inspector').hidden=name!=='simulation';$('#studioPanel').hidden=name==='simulation';render();}
$$('[data-screen]').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));
$('#showroomSelect').onchange=e=>{if(e.target.value==='legacy'){location.href='../../Showroom%20Manager.dc.html';}};
$('#mapOverlay').onchange=e=>{window.APS_SIMULATION?.setOverlay(e.target.value);$('#mapLegend').hidden=e.target.value==='none';$('#mapLegend').innerHTML=({visibility:'<b>Visibility sketch</b><br>🟠 Prime &nbsp; 🔵 Secondary &nbsp; 🟢 Commercial<br>Exposure is proposed from the entrance route and display position; site review pending.',duplicates:'<b>Repeated designs</b><br>Amber outlines identify movable repeats. Distinct finishes may be useful.',review:'<b>Placement review</b><br>Amber: review suggested · Coral: priority/exposure concern<br>Based on draft guidelines.',good:'<b>Justified placements</b><br>Green outlines show documented bookmatch or a fit with the configured placement guideline.'})[e.target.value]||'';};
function stats(){const m=state.review.summary;return `<div class="metric-grid">${[[m.unique_designs,'Designs currently represented'],[m.missing_designs,'Unrepresented catalogue designs'],[m.repeated_designs,'Designs with movable repeats'],[m.attention_slots,'Exposure / status concerns']].map(([n,label])=>`<div class="metric"><b>${n}</b><span>${label}</span></div>`).join('')}</div>`;}
function review(){
  const summary=state.review.summary,q=reviewSearch.toLowerCase();let rows='';
  if(reviewFilter==='duplicates')rows=state.review.duplicates.filter(r=>r.name.toLowerCase().includes(q)).map(r=>`<article class="review-row">${photo(r.product_id)}<div><b>${esc(r.name)}</b><small>${r.slot_ids.length} presentations · ${r.movable_count} movable · ${r.distinct_finishes} finishes</small>${chip(r.intentional?'Documented bookmatch':'Review duplication',r.intentional?'good':'review')}</div><p>${r.intentional?'Retain the intentional pairing.':r.distinct_finishes>1?'Different finishes are represented. Review useful variety before removing a repeat.':'A broader range may be possible by replacing one movable repeat.'}</p>${btn('Highlight on map','highlight',r.slot_ids.join('|'))}</article>`).join('');
  if(reviewFilter==='attention')rows=state.review.issues.filter(r=>r.level==='attention'&&`${pby(r.product_id)?.name} ${r.description}`.toLowerCase().includes(q)).map(r=>`<article class="review-row">${photo(r.product_id)}<div><b>${esc(pby(r.product_id)?.name)}</b><small>${esc(slotName(r.slot_id))}</small>${chip(r.code.replaceAll('_',' '),'attention')}</div><p>${esc(r.description)}</p>${btn('Inspect placement','slot',r.slot_id)}</article>`).join('');
  if(reviewFilter==='good')rows=state.review.good.filter(r=>pby(r.product_id)?.name.toLowerCase().includes(q)).map(r=>`<article class="review-row">${photo(r.product_id)}<div><b>${esc(pby(r.product_id)?.name)}</b><small>${esc(slotName(r.slot_id))}</small>${chip('Justified','good')}</div><p>${esc(r.description)}</p>${btn('Show on map','slot',r.slot_id)}</article>`).join('');
  if(reviewFilter==='missing')rows=state.review.missing.filter(r=>r.name.toLowerCase().includes(q)).map(r=>`<article class="review-row">${photo(r.product_id)}<div><b>${esc(r.name)}</b><small>${r.compatible_slot_ids.length} nominally compatible slots · SKU/release confirmation may be pending</small>${r.hit?chip('Hit','review'):chip('Portfolio option')}</div><p>${esc(r.alternative)}</p>${btn('Explore placement','new-product',r.product_id)}</article>`).join('');
  if(reviewFilter==='color')rows=state.review.issues.filter(r=>r.code==='color_order'&&`${pby(r.product_id)?.name} ${slotName(r.slot_id)}`.toLowerCase().includes(q)).map(r=>`<article class="review-row">${photo(r.product_id)}<div><b>${esc(pby(r.product_id)?.name)}</b><small>${esc(slotName(r.slot_id))}</small></div><p>${esc(r.description)}</p>${btn('Inspect run','slot',r.slot_id)}</article>`).join('');
  return heading('PLACEMENT REVIEW','A place for every design.','Review repetition, first-view exposure and the range customers can experience.',btn('Generate refresh','refresh-plan','','primary')+btn('Visibility map','visibility'))+stats()+
    `<div class="notice">${esc(state.review.basis)} Bookmatch pairs and protected live applications are excluded from routine replacement.</div><div class="filters">${[['duplicates','Repeated designs'],['attention','Review needed'],['good','Good placements'],['missing','Not represented'],['color','Color order']].map(([id,name])=>`<button data-action="review-filter" data-id="${id}" class="${id===reviewFilter?'active':''}">${name}</button>`).join('')}<input id="reviewSearch" type="search" value="${esc(reviewSearch)}" placeholder="Find a product…" aria-label="Filter placement review"></div><div id="reviewRows">${rows||'<div class="empty-note">No matching records in this view.</div>'}</div>`;
}
function proposalCard(p){
  const changes=p.changes,blocked=changes.some(c=>c.blockers?.length),stale=p.base_revision!==state.meta.revision;
  return `<article class="proposal-card"><div class="proposal-top"><div><h3>${esc(p.title)}</h3><small class="small-muted">${changes.length} changes · ${esc(p.actor)} · revision ${p.base_revision}</small></div>${chip(stale?'Source changed':p.status,stale?'attention':'')}${blocked?chip('Input needed','review'):''}<div class="screen-actions">${btn('Compare in 3D','preview',p.id)}${btn('Release work','release',p.id)}</div></div><div class="proposal-body"><details><summary>${p.evaluation.before.unique_designs} → ${p.evaluation.after.unique_designs} represented designs · view changes and dependencies</summary>${changes.map(c=>`<div class="change-row"><b>${esc(c.kind==='fixture'?c.fixture_id:slotName(c.slot_id))}</b><br>${c.kind==='placement'?`${esc(nameFor(c.from_variant_id))} → <strong>${esc(nameFor(c.variant_id))}</strong>`:`x ${c.from.x_mm}, z ${c.from.z_mm} → x ${c.to.x_mm}, z ${c.to.z_mm} mm`}<br>${esc(c.reason)}${c.blockers?.length?`<div class="blockers">Before release: ${esc([...new Set(c.blockers)].join(' '))}</div>`:''}</div>`).join('')}</details></div></article>`;
}
function work(){
  return heading('WORK PLAN','From a proposal to a place.','Draft the change, resolve its dependencies, then track ordering, preparation, installation and verification.',btn('Broader coverage','refresh-plan','','primary')+btn('Color sequence','color-plan')+btn('Move a fixture','fixture-form'))+
    (!connected?'<div class="notice amber">Published review snapshot. Compare the saved proposals here; start the local Studio to create drafts, release tasks or record installation progress.</div>':'<div class="notice">Merch releases work packages. Agents and designers can propose changes; showroom managers record actual progress. No order or message is sent to another system by this pilot.</div>')+
    `<div class="eyebrow">DESIGN PROPOSALS</div>${state.scenarios.slice().reverse().map(proposalCard).join('')||'<p>No proposals yet.</p>'}<div class="screen-heading" style="margin-top:35px"><div><h2>Installation & preparation</h2><p>Each card has an owner, optional due date, evidence and a disposition for removed material.</p></div></div><div class="board">${[['to_do','To do'],['ordered','Ordered'],['prepared','Prepared'],['installed','Installed'],['verified','Verified']].map(([stage,name])=>`<section class="board-column"><h3>${name} · ${state.tasks.filter(t=>t.stage===stage).length}</h3>${state.tasks.filter(t=>t.stage===stage).map(t=>`<button class="task-card" data-action="task" data-id="${t.id}"><b>${esc(t.title)}</b><small>${esc(t.owner)}<br>${t.due_date?'Due '+esc(t.due_date):'Date to agree'}${t.kind==='collect_input'?'<br>Guideline / data dependency':''}</small></button>`).join('')}</section>`).join('')}</div>`;
}
function data(){
  let content='';
  if(dataTab==='questions')content=`<div class="notice">Use these 12 decisions in the Sales, Merch and Interior Design workshop. Proposed answers are a starting sketch; saved answers keep an owner and evidence.</div>`+state.questions.map(q=>`<article class="question-card">${chip(q.team)}${chip(q.status,q.status==='answered'?'good':'')}<h3>${q.id} · ${esc(q.question)}</h3><p><b>Starting suggestion:</b> ${esc(q.proposed_answer)}</p>${q.answer?`<p><b>Team answer:</b> ${esc(q.answer)}</p>`:''}${btn(q.answer?'Update answer':'Record answer','question',q.id)}</article>`).join('');
  if(dataTab==='rules')content=`<div class="notice">User-confirmed policies are identified below. Draft brand, visibility and architectural rules require team review. Hard protections remain enforced by the application even if their display toggle is edited.</div><table class="source-table"><thead><tr><th>Rule</th><th>Behavior / current parameters</th><th>Owner & status</th><th></th></tr></thead><tbody>${state.rules.map(r=>`<tr><td>${r.id} · ${esc(r.name)}<br>${chip(r.strength)}</td><td>${esc(r.rationale)}<br><code>${esc(JSON.stringify(r.parameters))}</code></td><td>${esc(r.owner)}<br>${chip(r.status,r.status==='confirmed'?'good':'review')}</td><td>${btn('Edit','rule',r.id)}</td></tr>`).join('')}</tbody></table>`;
  if(dataTab==='products')content=`<div class="notice">Positioning and Hit are separate fields. Lifecycle and stock remain unconfirmed until Sales/Product provides evidence. Source names that may be aliases remain visible for Merch reconciliation.</div><input id="catalogSearch" type="search" placeholder="Filter the product catalogue…" aria-label="Filter products"><table class="source-table"><thead><tr><th>Design / family</th><th>Positioning</th><th>Lifecycle</th><th>Color group / rank</th><th></th></tr></thead><tbody id="catalogRows">${state.products.map(p=>`<tr data-product-name="${esc(p.name.toLowerCase())}"><td>${esc(p.name)}<br><small>${esc(p.family)}</small></td><td>${chip(p.positioning)}${p.hit?chip('Hit','review'):''}</td><td>${esc(p.lifecycle)}</td><td>${esc(p.color_group)} / ${p.color_rank??'—'}</td><td>${btn('Edit','product',p.id)} ${btn('Variants','variants',p.id)}</td></tr>`).join('')}</tbody></table>`;
  if(dataTab==='files')content=`<div class="two-col"><article class="content-card"><h3>One authoritative source</h3><p>SQLite owns placements, rules, tasks and evidence. CSV exports are editable exchange files with a base revision. Import validates the entire file before saving.</p><a href="../data/showroom.sqlite" download>↓ SQLite database</a><a href="data/state.json" download>↓ Review snapshot JSON</a><p>${btn('Refresh exported files','export','','primary')}</p><p class="small-muted">Refreshing files updates the local snapshot. Publishing a new GitHub version is a separate Git push.</p></article><article class="content-card"><h3>Human-readable tables</h3>${['products','variants','slots','fixtures','placements','rules','questions','tasks'].map(t=>`<a href="../data/exports/${t}.csv" download>↓ ${t}.csv</a>`).join('')}<p>Placement imports create draft scenarios. Direct edits to CSV files do not silently change the installed scene.</p>${btn('Validate / import CSV','csv-form')}</article></div><article class="content-card"><h3>Production faces & source evidence</h3><p>${state.faces.length} production previews are registered by design, source format and hash. The exact installed face is unverified. Missing matches retain the source preview.</p><div class="source-list"><a href="../docs/DATA_AND_ASSETS.md">Data contract & asset format guide ↗</a><a href="../docs/TEAM_DECISIONS.md">Concise team workshop sheet ↗</a><a href="../docs/ROADMAP.md">Implementation roadmap ↗</a><a href="../docs/AGENT_CONTRACT.md">Agent / MCP contract ↗</a><a href="../docs/archive/Source_Pack_and_3D_Simulation.md">Original source review ↗</a></div></article>`;
  return heading('DATA & GUIDELINES','Make the rules explicit.','A shared template for the decisions that drive the showroom.')+`<div class="filters">${[['questions','Team decisions'],['rules','Design rules'],['products','Product portfolio'],['files','Source files & import']].map(([id,name])=>`<button data-action="data-tab" data-id="${id}" class="${id===dataTab?'active':''}">${name}</button>`).join('')}</div>`+content;
}
function process(){return heading('OPERATING MODEL','One source. A complete journey.','A practical foundation for an end-to-end design system, with the same rules available to Merch, designers and agents.')+
  `<div class="process-flow">${[
    ['Source of truth','Products, faces, architectural slots and reported installations live in SQLite. Human edits enter through validated CSV or forms.','Sales + Merch + showroom','data'],
    ['Evaluate the showroom','Measure coverage, repeats, visibility and color order. Keep uncertainty and intentional exceptions visible.','Deterministic rules','review'],
    ['Design a proposal','Replace movable repeats first. Compare variants and bounded fixture moves in the 3D scene.','System · agent · designer','work'],
    ['Release a work package','Merch resolves SKU, stock, fixture compatibility and layout dependencies before authorizing work.','Merch authority','work'],
    ['Order, prepare, install','Track the responsible person, materials, dates and evidence. Record where removed slabs and panels go.','Merch + installation team','work'],
    ['Verify and learn','Physical verification updates the placement record and simulation. Future launches and feedback start the next review.','Showroom manager','simulation']
  ].map(([title,desc,owner,target])=>`<button class="flow-step" data-action="screen" data-id="${target}"><h3>${title}</h3><p>${desc}</p><strong>${owner} →</strong></button>`).join('')}</div><div class="feedback-loop">↺ &nbsp; A new launch, discontinuation, sales signal or customer observation triggers the next evaluation.<p>Every proposal cites a source revision. Actual installations change only when recorded with evidence.</p></div><div class="two-col"><article class="content-card"><h3>First example: Tuscano Burgundy</h3><p>Tuscano Rosso is retained as an alias. The design can be previewed in a prime movable slot while SKU, stock and fixture compatibility remain visible dependencies.</p>${btn('Compare the proposal','tuscano-preview','','primary')}</article><article class="content-card"><h3>Future agent control</h3><p>The MCP adapter reads the same data and creates proposals through the same validation functions. Sales feeds, feedback capture, multi-user authentication and automatic follow-up are the next integration layer.</p><a href="../docs/process.svg" target="_blank">Open the process sketch ↗</a><a href="../docs/AGENT_CONTRACT.md">Read the agent contract ↗</a></article></div>`;}
function render(){updateHeader();if(screen!=='simulation')$('#studioPanel').innerHTML=({review,work,data,process})[screen]();}
function openDialog(title,html,onSubmit){$('#editTitle').textContent=title;$('#editBody').innerHTML=`<form id="studioForm">${html}</form>`;$('#editError').textContent='';$('#editDialog').showModal();dialogAction=onSubmit;$('#studioForm').onsubmit=async e=>{e.preventDefault();const b=$('#studioForm button[type=submit]');if(b)b.disabled=true;try{await dialogAction(Object.fromEntries(new FormData(e.target)));$('#editDialog').close();await sync();}catch(error){$('#editError').textContent=error.message;}finally{if(b)b.disabled=false;}};}
$('#closeEdit').onclick=()=>$('#editDialog').close();
const submit=label=>`<button class="primary" type="submit">${label}</button>`;
const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}"></label>`;
const selectField=(name,label,options,value)=>`<label>${label}<select name="${name}">${options.map(x=>{const v=Array.isArray(x)?x[0]:x,t=Array.isArray(x)?x[1]:x;return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
const textField=(name,label,value='')=>`<label class="wide">${label}<textarea name="${name}">${esc(value)}</textarea></label>`;
const localNote=()=>connected?'':`<div class="notice amber">Read-only public review. These inputs can be explored; saving requires the local Studio connected to SQLite.</div>`;
async function sync(){await refresh();await window.APS_SIMULATION?.applySnapshot(state,activeProposal?state.scenarios.find(p=>p.id===activeProposal):null);render();}
async function propose(payload){const r=await request('propose',payload);await refresh();activeProposal=r.scenario_id;setScreen('work');toast('Draft saved. The reported installation is unchanged.');}
async function preview(id){const p=state.scenarios.find(p=>p.id===id);if(!p)return;activeProposal=id;setScreen('simulation');$('#mapOverlay').value='none';$('#mapLegend').hidden=true;document.querySelector('[data-view=orbit]').click();await window.APS_SIMULATION?.applySnapshot(state,p);$('#proposalBanner').hidden=false;$('#proposalBanner').innerHTML=`<b>PROPOSAL · ${p.changes.length} CHANGES</b><br>${esc(p.title)}<br>Installed record retained.<br>${btn('Return to current','current')}${btn('View work plan','screen','work')}`;const first=p.changes[0]?.slot_id||state.slots.find(s=>s.fixture_id===p.changes[0]?.fixture_id)?.id;if(first)window.APS_SIMULATION?.selectSlot(first);}
function productForm(id){const p=pby(id);openDialog('Product guidelines · '+p.name,localNote()+`<div class="form-grid">${selectField('positioning','Positioning',['unknown','prime','commercial'],p.positioning)}${selectField('hit','Hit flag',[[0,'No'],[1,'Yes']],p.hit)}${selectField('lifecycle','Product lifecycle',['unconfirmed','active','discontinued'],p.lifecycle)}${selectField('required','Required in APS',[[0,'No'],[1,'Yes']],p.required)}${field('color_group','Color group',p.color_group)}${field('color_rank','Color rank (ascending = light to dark)',p.color_rank,'number')}${field('priority_source','Decision source / owner',p.priority_source)}${textField('notes','Guideline notes',p.notes)}</div>${submit('Save product guidelines')}`,async values=>{await request('edit',{table:'products',records:[{id,...values}]});toast('Guidelines saved to SQLite.');});}
function variantForm(productId){const options=state.variants.filter(v=>v.product_id===productId);const v=options[0];openDialog('Variant release data · '+pby(productId).name,localNote()+`<div class="form-row">${selectField('id','Variant',options.map(v=>[v.id,`${v.sku||'No SKU'} · ${v.width_mm} × ${v.height_mm} · ${v.finish}`]),v?.id)}</div><div id="variantFields"></div>${submit('Save release data')}`,async values=>{await request('edit',{table:'variants',records:[values]});});
  const fill=()=>{const v=vby($('#studioForm [name=id]').value);$('#variantFields').innerHTML=`<div class="form-grid">${field('sku','Released SKU',v.sku)}${field('finish','Finish',v.finish)}${field('width_mm','Width (mm)',v.width_mm,'number')}${field('height_mm','Height (mm)',v.height_mm,'number')}${field('thickness_mm','Thickness (mm)',v.thickness_mm,'number')}${selectField('lifecycle','Lifecycle',['unconfirmed','active','discontinued'],v.lifecycle)}${selectField('availability','Availability',['unknown','installed_reference','available','unavailable'],v.availability)}</div>`;};$('#studioForm [name=id]').onchange=fill;fill();}
function slotForm(id){const slot=sby(id),a=state.placements.find(a=>a.slot_id===id),v=vby(a.variant_id);openDialog(slot.title,localNote()+`<p>${esc(nameFor(a.variant_id))} · ${esc(id)}<br>${chip(slot.visibility_tier)}${chip(slot.locked?'Protected application':'Movable display')}</p><p>${esc(slot.visibility_basis)}</p><div class="form-row">${selectField('product_id','Product',state.products.map(p=>[p.id,p.name]),v?.product_id)}</div><div class="form-row" id="slotVariants"></div><div class="form-row">${selectField('operation','Action',[['proposal','Propose a replacement'],['observe','Record what is physically installed']],slot.locked?'observe':'proposal')}</div><div class="form-row">${textField('evidence','Observation evidence / proposal reason')}</div>${submit('Save through source validation')}<p class="small-muted">Observations document reality, including changes to protected surfaces. Proposals must satisfy the replacement rules.</p>`,async values=>{
    if(values.operation==='observe')await request('observe',{slot_id:id,variant_id:values.variant_id,evidence:values.evidence});
    else await request('propose',{mode:'manual',changes:[{kind:'placement',slot_id:id,from_variant_id:a.variant_id,variant_id:values.variant_id,reason:values.evidence||'Merch/designer proposal from the selected slot.'}]});toast(values.operation==='observe'?'Physical observation saved.':'Replacement saved as a draft.');
  });const fill=()=>{$('#slotVariants').innerHTML=selectField('variant_id','Variant / format',state.variants.filter(v=>v.product_id===$('#studioForm [name=product_id]').value).map(v=>[v.id,`${v.sku||'SKU pending'} · ${v.width_mm||'?'} × ${v.height_mm||'?'} · ${v.finish}`]),a.variant_id);};$('#studioForm [name=product_id]').onchange=fill;fill();}
function fixtureForm(){const fs=state.fixtures.filter(f=>f.relocatable);openDialog('Fixture position study',localNote()+'<p>Move a fixed-panel frame with both faces attached. Bounds, protected rooms, frame collisions and the draft central route are checked. Measured travel/load/brand approval is still needed before release.</p>'+`<div class="form-row">${selectField('fixture_id','Fixture',fs.map(f=>[f.id,f.id]),fs[0]?.id)}</div><div id="moveFields"></div>${submit('Validate and create proposal')}`,async values=>{await propose({mode:'fixture',fixture_id:values.fixture_id,target:{x_mm:Number(values.x_mm),z_mm:Number(values.z_mm),yaw_deg:Number(values.yaw_deg)}});});
  const fill=()=>{const f=fs.find(f=>f.id===$('#studioForm [name=fixture_id]').value);$('#moveFields').innerHTML=`<div class="form-grid">${field('x_mm','X from plan origin (mm)',f.x_mm,'number')}${field('z_mm','Z from plan origin (mm)',f.z_mm,'number')}${field('yaw_deg','Rotation (degrees)',f.yaw_deg,'number')}</div>`;};$('#studioForm [name=fixture_id]').onchange=fill;fill();}
function taskForm(id){const t=state.tasks.find(t=>t.id===id);openDialog(t.title,localNote()+`<div class="form-grid">${field('owner','Responsible person / team',t.owner)}${field('due_date','Due date',t.due_date,'date')}${selectField('stage','Progress',['to_do','ordered','prepared','installed','verified'],t.stage)}${textField('evidence','Evidence / receipt / installation reference',t.evidence)}${textField('disposition','Removed material destination (or no removal)',t.disposition)}</div>${submit('Record progress')}<p class="small-muted">Verification of an installation updates the actual placement and simulation in the same database transaction.</p>`,async values=>{await request('task',{id,...values});toast('Work progress saved.');});}
function csvForm(){openDialog('Validate / import a CSV',localNote()+`<p>Export the current revision, edit the intended fields, then validate the file here. A placement import produces a draft; it cannot mark materials as installed.</p><div class="form-row">${selectField('table','Table',['products','variants','slots','fixtures','placements','rules','questions'],'products')}</div><div class="form-row"><label>CSV file<input id="csvFile" type="file" accept=".csv,text/csv" required></label></div><div class="form-row">${selectField('mode','Import action',[['validate','Validate only'],['apply','Validate and save']],'validate')}</div>${submit('Run validated import')}`,async values=>{const file=$('#csvFile').files[0];if(!file)throw Error('Choose a CSV file.');const result=await request('import',{table:values.table,csv:await file.text(),dry_run:values.mode!=='apply'});toast(values.mode==='apply'?'Validated changes saved.':'Validation passed; no source data changed.');});}
document.addEventListener('input',e=>{
  if(e.target.id==='reviewSearch'){reviewSearch=e.target.value;const pos=e.target.selectionStart;render();$('#reviewSearch').focus();$('#reviewSearch').setSelectionRange(pos,pos);}
  if(e.target.id==='catalogSearch')$$('#catalogRows tr').forEach(row=>row.hidden=!row.dataset.productName.includes(e.target.value.toLowerCase()));
});
document.addEventListener('click',async e=>{
  const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;
  try{
    if(action==='screen')setScreen(id);
    if(action==='data-tab'){dataTab=id;render();}
    if(action==='review-filter'){reviewFilter=id;render();}
    if(action==='visibility'){setScreen('simulation');$('#mapOverlay').value='visibility';$('#mapOverlay').dispatchEvent(new Event('change'));}
    if(action==='highlight'){setScreen('simulation');window.APS_SIMULATION?.setOverlay('selected',id.split('|'));window.APS_SIMULATION?.selectSlot(id.split('|')[0]);}
    if(action==='slot'){setScreen('simulation');window.APS_SIMULATION?.selectSlot(id);}
    if(action==='refresh-plan')await propose({mode:'refresh'});
    if(action==='color-plan')await propose({mode:'color_order'});
    if(action==='new-product'){
      if(!connected){const p=state.scenarios.find(p=>p.mode==='new_product'&&p.changes.some(c=>vby(c.variant_id)?.product_id===id));if(p)await preview(p.id);else toast('Start the local Studio to generate a proposal for '+pby(id)?.name+'.');}
      else await propose({mode:'new_product',product_id:id});
    }
    if(action==='tuscano-preview'){const p=state.scenarios.find(p=>p.mode==='new_product');if(p)await preview(p.id);}
    if(action==='preview')await preview(id);
    if(action==='current'){activeProposal=null;$('#proposalBanner').hidden=true;await window.APS_SIMULATION?.applySnapshot(state);$('#mapOverlay').value='none';$('#mapLegend').hidden=true;}
    if(action==='release'){await request('release',{id});await sync();toast('Merch released the work package; tasks created.');}
    if(action==='product')productForm(id);
    if(action==='variants')variantForm(id);
    if(action==='fixture-form')fixtureForm();
    if(action==='task')taskForm(id);
    if(action==='csv-form')csvForm();
    if(action==='export'){await request('export');toast('CSV and review snapshot exported from SQLite.');}
    if(action==='question'){const q=state.questions.find(q=>q.id===id);openDialog(q.id+' · '+q.team,localNote()+`<p>${esc(q.question)}</p><div class="form-grid">${textField('answer','Team answer',q.answer)}${field('owner','Decision owner',q.owner)}${selectField('status','Status',['open','answered','needs_review'],q.status)}${textField('evidence','Evidence / decision reference',q.evidence)}</div>${submit('Save team decision')}`,async values=>{await request('edit',{table:'questions',records:[{id,...values}]});});}
    if(action==='rule'){const r=state.rules.find(r=>r.id===id);openDialog(r.id+' · '+r.name,localNote()+`<p>${esc(r.rationale)}</p><div class="form-grid">${selectField('enabled','Evaluate this rule',[[1,'Enabled'],[0,'Disabled']],r.enabled)}${selectField('status','Team status',['draft','confirmed'],r.status)}${textField('parameters_json','Parameters (JSON)',JSON.stringify(r.parameters,null,2))}${textField('rationale','Reason / evidence for guideline',r.rationale)}</div>${submit('Save rule')}`,async values=>{await request('edit',{table:'rules',records:[{id,...values}]});});}
  }catch(error){toast(error.message);}
});
window.addEventListener('studio:slot',e=>slotForm(e.detail));
window.STUDIO={getState:()=>state,getScreen:()=>screen,setScreen,refresh:sync,preview};
render();
